blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from django.views.decorators.cache import cache_page

app_name = BlogConfig.name

urlpatterns = [
    path("list/", cache_page(60)(BlogListView.as_view()), name="blog_list"),
    path("detail/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="blog_delete"),
]

client/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from client.views import ClientListView, ClientDetailView, ClientUpdateView, ClientCreateView, ClientDeleteView

urlpatterns = [
    path('client/list', ClientListView.as_view(), name='client_list'),
    path('client/create', ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/detail', ClientDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/update', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete', ClientDeleteView.as_view(), name='client_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include(('client.urls', 'client'), namespace='client')),
                  path('messenger/', include(('messenger.urls', 'messenger'), namespace='messenger')),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
                  path('blog/', include(('blog.urls', 'blog'), namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messenger/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from messenger.services import send_letters
from messenger.views import MessageListView, MessageCreateView, MessageDetailView, MessageUpdateView, MessageDeleteView, \
    send_newsletter, MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingDetailView, \
    MailingsChangeStatusView, home


urlpatterns = [
    # Messenger URLS
    path('message/list/', MessageListView.as_view(), name='message_list'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/detail/', MessageDetailView.as_view(), name='message_detail'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('send_letters/<int:pk>/', send_letters, name='send_letters'),

    # Mailings URLS
    path('mailing/list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/detail/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path("mailing_change_status/<int:pk>/", MailingsChangeStatusView.as_view(), name="mailings_change_status"),

    # Home page
    path('home-page/', cache_page(60)(home), name='home'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import UserCreateView, email_confirmation, PasswordRecoveryView, UserUpdateView

urlpatterns = [

    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_confirmation, name='email'),
    path('password-reset/', PasswordRecoveryView.as_view(), name='password_reset'),

    path("update_user/<int:pk>/", UserUpdateView.as_view(), name="update_user")
]

client/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='почта')
    full_name = models.CharField(max_length=150, verbose_name='полное имя')
    comment = models.TextField(**NULLABLE, verbose_name='о клиенте')
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Владелец", **NULLABLE)

    def __str__(self):
        return f"{self.full_name} ({self.email})"

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

client/forms.py
from django.forms import ModelForm, BooleanField

from client.models import Client


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        fields = ['email', 'full_name', 'comment']

client/views.py
from django.shortcuts import render
from client.models import Client
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView
from django.urls import reverse_lazy, reverse
from client.forms import ClientForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='moder'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('client:client_list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        user = self.request.user
        self.object.owner = user

        return super().form_valid(form)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='moder') and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    success_url = reverse_lazy('client:client_list')
    form_class = ClientForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('client:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object

client/templates/client/includes/inc_menu.html
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <h4>О нас</h4>
                <p class="text-body-secondary">Мы - ваш надежный партнер в создании здорового образа жизни и радостных
                    моментов. В нашем ассортименте только самые свежие и качественные овощи и фрукты, которые не только
                    дарят радость своим вкусом, но и поддерживают ваше здоровье. Мы гордимся тем, что каждый день
                    предлагаем вам лучшее из мира природы, чтобы вы могли наслаждаться вкусом и получать максимум пользы
                    для своего организма. Доверьтесь нам и делайте свой выбор в пользу здоровья и радости!"</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
                <h4>Навигация</h4>
                <ul class="list-unstyled">
                    <li><a href="{% url 'messenger:home' %}" class="text-white">Главная</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'users:logout' %}" class="text-white">Выход</a></li>
                    {% else %}
                    <li><a href="{% url 'users:login' %}" class="text-white">Вход</a></li>
                    <li><a href="{% url 'users:register' %}" class="text-white">Регистрация</a></li>
                    <li><a href="{% url 'users:password_reset' %}" class="text-white">Забыли пароль?</a></li>
                    {% endif %}
                    <li><a href="{% url 'client:client_list' %}" class="text-white">Клиенты</a></li>
                    <li><a href="{% url 'messenger:message_list' %}" class="text-white">Сообщения</a></li>
                    <li><a href="{% url 'messenger:mailing_list' %}" class="text-white">Рассылки</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">
            <strong>Меню</strong>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>