blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from django.views.decorators.cache import cache_page

app_name = BlogConfig.name

urlpatterns = [
    path("list/", cache_page(60)(BlogListView.as_view()), name="blog_list"),
    path("detail/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include(('client.urls', 'client'), namespace='client')),
                  path('messenger/', include(('messenger.urls', 'messenger'), namespace='messenger')),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
                  path('blog/', include(('blog.urls', 'blog'), namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messenger/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from messenger.services import send_letters
from messenger.views import MessageListView, MessageCreateView, MessageDetailView, MessageUpdateView, MessageDeleteView, \
    send_newsletter, MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingDetailView, \
    MailingsChangeStatusView, home


urlpatterns = [
    # Messenger URLS
    path('message/list/', MessageListView.as_view(), name='message_list'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/detail/', MessageDetailView.as_view(), name='message_detail'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('send_letters/<int:pk>/', send_letters, name='send_letters'),

    # Mailings URLS
    path('mailing/list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/detail/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path("mailing_change_status/<int:pk>/", MailingsChangeStatusView.as_view(), name="mailings_change_status"),

    # Home page
    path('home-page/', cache_page(60)(home), name='home'),

]

messenger/models.py
from django.db import models
from client.models import Client, NULLABLE
from users.models import User


class Message(models.Model):
    subject = models.CharField(max_length=255, verbose_name='оглавление сообщения')
    body = models.TextField(verbose_name='тело сообщения')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Владелец", **NULLABLE)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):
    CREATED = 'created'
    COMPLETED = 'completed'
    STARTED = 'started'
    STATUS_CHOICES = (
        ('created', 'Created'),
        ('started', 'Started'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    )
    first_send_time = models.DateTimeField(verbose_name='время первой отправки')
    last_send_time = models.DateTimeField(**NULLABLE, verbose_name='время конечной отправки')
    next_send_time = models.DateTimeField(**NULLABLE, verbose_name='время следующей отправки')
    periodicity = models.CharField(max_length=50,
                                   choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')],
                                   default='daily', verbose_name='периодичность')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='created', verbose_name='статус')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='сообщение')
    client = models.ManyToManyField(Client, verbose_name='клиент')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Владелец", **NULLABLE)

    def __str__(self):
        return (f'{self.status} {self.message} {self.first_send_time} {self.last_send_time} {self.periodicity} '
                f'{self.client}')

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [("can_change_status", "Может менять статус")]


class Attempt(models.Model):
    SUCCESS = 'successful'
    FAIL = 'failed'
    STATUS_CHOICES = (
        ('success', 'Success'),
        ('failed', 'Failed'),
    )
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, related_name='attempts')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, **NULLABLE)
    attempt_time = models.DateTimeField(auto_now_add=True, verbose_name='попытка рассылки')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, verbose_name='статус')
    response = models.TextField(blank=True, null=True, verbose_name='ответ сервера')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='время создания')

    def __str__(self):
        return f'{self.status} {self.created_at} {self.response} {self.attempt_time} {self.client}'

    class Meta:
        verbose_name = 'Попытка'
        verbose_name_plural = 'Попытки'

messenger/forms.py
from django.forms import ModelForm, ModelChoiceField, BooleanField
from client.forms import StyleFormMixin
from client.models import Client
from messenger.models import Message, Mailing


class MessageForm(ModelForm, StyleFormMixin):
    class Meta:
        model = Message
        fields = ['subject', 'body']


class MailingForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        exclude = ('owner', 'status')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super().__init__(*args, **kwargs)
        if self.request:
            user = self.request.user
            self.fields["client"].queryset = Client.objects.filter(owner=user)
            self.fields["message"].queryset = Message.objects.filter(owner=user)


class MailingChangeStatusForm(StyleFormMixin):
    class Meta:
        model = Mailing
        fields = ("status",)

messenger/views.py
import random
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from blog.models import Blog
from client.models import Client
from messenger.forms import MessageForm, MailingForm, MailingChangeStatusForm
from messenger.models import Message, Mailing
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseBadRequest
from messenger.utils import send_mailing
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='moder'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('messenger:message_list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        user = self.request.user
        self.object.owner = user

        return super().form_valid(form)


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='moder') and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('messenger:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('messenger:message_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    form_class = MailingForm

    def get_queryset(self, queryset=None):
        queryset = super().get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='moder'):
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('messenger:message_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # if not self.request.user.is_superuser:
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form):
        """Добавление владельца рассылке"""
        mailing = form.save()
        user = self.request.user
        mailing.owner = user
        mailing.save()
        return super().form_valid(form)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing
    form_class = MailingForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='moder') and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and not user.groups.filter(name='moder') and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    form_class = MailingForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        user = self.request.user
        if not user.is_superuser and user != self.object.owner:
            raise PermissionDenied
        else:
            return self.object


class MailingsChangeStatusView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    template_name = "mailings_app/mailing_change_status.html"
    form_class = MailingChangeStatusForm
    success_url = reverse_lazy("messenger:mailing_list")
    permission_required = ("messenger.can_change_status",)


def send_newsletter(request, newsletter_id):
    try:  # Вызываем функцию для отправки рассылки
        send_mailing()
        return HttpResponse("Рассылка отправлена успешно!")
    except Exception as e:
        return HttpResponseBadRequest(f'Ошибка при отрпавке рассылки {e}')


def home(request):
    total_mailings = Mailing.objects.count()
    active_mailings = Mailing.objects.filter(status=Mailing.STARTED).count()
    unique_clients = Client.objects.distinct().count()

    # Получение случайных трех статей из блога
    blog_posts = list(Blog.objects.all())
    random_articles = random.sample(blog_posts, 3) if len(blog_posts) >= 3 else blog_posts

    context = {
        'total_mailings': total_mailings,
        'active_mailings': active_mailings,
        'unique_clients': unique_clients,
        'random_articles': random_articles
    }
    return render(request, 'messenger/home.html', context)

messenger/templates/messenger/base.html
<!doctype html>
{% load static %}
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Obst und Gemüse</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    {% include 'client/includes/inc_menu.html' %}
</header>

<main>

    {% block content %}
    {% endblock %}

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">На верх</a>
        </p>
        <p class="mb-1">2024-{% now "Y" %}</p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

messenger/templates/messenger/home.html
<!DOCTYPE html>
{% extends 'client/base.html' %}

{% block content %}
<style>
    body {
        font-family: Arial, sans-serif;
    }
    .container {
        display: flex;
        justify-content: center;
        margin-top: 20px;
    }
    .content {
        display: flex;
        max-width: 12000px;
        width: 100%;
    }
    .blogs {
        flex: 2;
        display: flex;
        justify-content: space-around;
    }
    .card {
        width: 30%;
        margin: 10px;
    }
    .sidebar {
        flex: 1;
        background: #f9f9f9;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }
    .sidebar h2 {
        font-size: 20px;
        margin-bottom: 10px;
    }
    .sidebar p {
        font-size: 14px;
        color: #333;
    }
</style>
</head>
<head>
    <div>
        <div class="container d-flex flex-column justify-content-center align-items-center" style="height: 20vh;">
            <div class="row py-lg-4">
                <div class="col text-center">
                    <h1 class="fw-light">Добро пожаловать!</h1>
                    <p class="lead text-body-secondary">Представляем вашему вниманию наш сервис для рассылок различных
                        сообщений.</p>
                </div>
            </div>
        </div>
    </div>
</head>
<body>
<div class="container">
    <div class="content">
        <div class="blogs">
            {% for article in random_articles %}
            <div class="card">
                <img src="{{ article.image.url }}" class="card-img-top" alt="{{ article.title }}">
                <div class="card-body">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <p class="card-text">{{ article.short_description }}</p>
                    <a href="{% url 'blog:blog_detail' article.pk %}" class="btn btn-primary">Просмотр</a>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="sidebar">
            <h2>Статистика</h2>
            <p>Количество рассылок всего: {{ total_mailings }}</p>
            <p>Количество активных рассылок: {{ active_mailings }}</p>
            <p>Количество уникальных клиентов для рассылок: {{ unique_clients }}</p>
        </div>
    </div>
</div>
</body>
</html>

{% endblock %}

messenger/templates/messenger/mailing_change_status.html
{% extends 'client/base.html' %}

{% block content %}

<br>
    <form method="post" enctype="multipart/form-data">
        <div class="row">

            <div class="col-1">
            </div>

        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Изменение статуса рассылки
                    </div>
                </div>
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}

                    <button type="submit" class="btn btn-success">Подтвердить изменения</button>

                </div>
            </div>
        </div>
             <div class="col-2">

             </div>

            <div class="col-1">
            </div>

        </div>
    </form>

{% endblock %}

messenger/templates/messenger/mailing_confirm_delete.html
{% extends 'client/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-8 mx-auto">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text"> Хотите удалить рассылку?</p>
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Удалить</button>
                            <a class="btn btn-dark" href="{% url 'messenger:mailing_list' %}" role="button">Назад</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

messenger/templates/messenger/mailing_detail.html
{% extends 'messenger/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-title"><p class="card-text">{{ object.slug }}</p>
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                             xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                             preserveAspectRatio="xMidYMid slice" focusable="false">
                        </svg>
                        <div class="card-body">
                            <p class="card-text">{{ object.name }}</p>
                            <p class="card-text">{{ object.description }}</p>
                            <p class="card-text">Добавил пользователь: {{object.owner}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="{% url 'messenger:mailing_list' %}"
                                       role="button">Назад</a>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            Просмотры: {{object.views}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

messenger/templates/messenger/mailing_list.html
{% extends 'client/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <a class="btn btn-outline-primary" href="{% url 'messenger:mailing_create' %}"
           role="button">Создать новою рассылку:</a>
        <br>
        <br>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">Оглавление рассылки: {{ object.message.subject}}</p>
                        <p class="card-text">Статус: {{ object.status}}</p>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-outline-warning" href="{% url 'messenger:mailing_update' object.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-outline-primary" href="{% url 'messenger:mailing_detail' object.pk %}"
                                   role="button">Описание</a>
                                <a class="btn btn-outline-danger" href="{% url 'messenger:mailing_delete' object.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

messenger/templates/messenger/message_list.html
{% extends 'client/base.html' %}
{% load my_tags %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <a class="btn btn-outline-primary" href="{% url 'messenger:message_create' %}"
           role="button">Создать сообщение:</a>
        <br>
        <br>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ object.subject }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-outline-warning" href="{% url 'messenger:message_update' object.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-outline-primary" href="{% url 'messenger:message_detail' object.pk %}"
                                   role="button">Описание</a>
                                <a class="btn btn-outline-danger" href="{% url 'messenger:message_delete' object.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}