blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView
from django.views.decorators.cache import cache_page

app_name = BlogConfig.name

urlpatterns = [
    path("list/", cache_page(60)(BlogListView.as_view()), name="blog_list"),
    path("detail/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include(('client.urls', 'client'), namespace='client')),
                  path('messenger/', include(('messenger.urls', 'messenger'), namespace='messenger')),
                  path('users/', include(('users.urls', 'users'), namespace='users')),
                  path('blog/', include(('blog.urls', 'blog'), namespace='blog'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messenger/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from messenger.services import send_letters
from messenger.views import MessageListView, MessageCreateView, MessageDetailView, MessageUpdateView, MessageDeleteView, \
    send_newsletter, MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, MailingDetailView, \
    MailingsChangeStatusView, home


urlpatterns = [
    # Messenger URLS
    path('message/list/', MessageListView.as_view(), name='message_list'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/detail/', MessageDetailView.as_view(), name='message_detail'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),

    path('send_letters/<int:pk>/', send_letters, name='send_letters'),

    # Mailings URLS
    path('mailing/list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing/<int:pk>/detail/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path("mailing_change_status/<int:pk>/", MailingsChangeStatusView.as_view(), name="mailings_change_status"),

    # Home page
    path('home-page/', cache_page(60)(home), name='home'),

]

blog/models.py
from django.db import models

NULLABLE = {"blank": True, "null": True}


class Blog(models.Model):
    title = models.CharField(max_length=50, verbose_name="Заголовок")
    body = models.TextField(verbose_name="Содержимое статьи")
    image = models.ImageField(upload_to='blog/', verbose_name='Изображение', **NULLABLE)
    view_count = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')
    created_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата публикации', **NULLABLE)

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from blog.models import Blog


class StyleMixin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class BlogForm(StyleMixin):
    class Meta:
        model = Blog
        exclude = ('view_count',)

blog/views.py
from blog.services import get_data_from_cache
from django.shortcuts import render

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from blog.forms import BlogForm
from blog.models import Blog

from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        return get_data_from_cache()


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy("blog:blog_list")

    def test_func(self):
        user = self.request.user
        if user.is_superuser:
            return True
        return False


class BlogUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy("blog:blog_list")

    def test_func(self):
        user = self.request.user
        if user.is_superuser:
            return True
        return False


class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")

    def test_func(self):
        user = self.request.user
        if user.is_superuser:
            return True
        return False

blog/templates/blog/blog_confirm_delete.html
{% extends 'client/base.html' %}

{% block content %}

<br>

<div class="container">
    <h5 class="text-center">Действительно желаете удалить '{{object.title}}'?</h5>
        <div class="text-center">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <a class="btn btn-light m-3" href="{% url 'blog:blog_detail' object.pk %}">Отменить</a>
                <button type="submit" class="btn btn-danger m-3">Да, удалить</button>
            </form>
        </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'client/base.html' %}

{% block content %}
<div class="container">
    <h1 class="text-center">{{object.title}}</h1>
    <div class="text-end">
        {% if user.is_superuser %}
        <a class="btn btn-outline-secondary" href="{% url 'blog:blog_update' object.pk %}">Редактировать</a>
        <a class="btn btn-outline-danger" href="{% url 'blog:blog_delete' object.pk %}">Удалить</a>
        {% endif %}
        <a class="btn btn-outline-primary" href="{% url 'messenger:home' %}">Назад</a>
    </div>

    <div class="container">
        <br>
        <div class="row">
            <div class="col-3">
                <div class="card text-center" style="width: 18rem;">
                    <div class="card-header">
                        {% if object.image %}
                        <img src="{{ object.image.url }}" class="img-thumbnail" style="width: 300px; height: 300px;">
                        {% endif %}
                    </div>
                    <div class="card-body">
                    </div>
                    <div class="card-footer">
                        <p class="text-center">Количество просмотров: {{object.view_count}}</p>
                        <p class="text-center">Публикация: {{object.created_at}}</p>
                    </div>
                </div>
            </div>
            <div class="col-8">
                <p>
                    {{object.body}}
                </p>
            </div>
            <div class="col-1">

            </div>

        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'client/base.html' %}

{% block content %}

<br>
    <form method="post" enctype="multipart/form-data">
        <div class="row">

            <div class="col-1">
            </div>

        <div class="col-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        {% if object %}
                            <h3>Редактирование</h3>
                        {% else %}
                            <h3>Добавление</h3>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}

                    {% if object %}
                        <button type="submit" class="btn btn-success">Подтвердить изменения</button>
                    {% else %}
                        <button type="submit" class="btn btn-success">Добавить</button>
                    {% endif %}


                </div>
            </div>
        </div>

        </div>
    </form>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'client/base.html' %}

{% block content %}
<br>
<div class="container">
    <div class="text-end">
        {% if user.is_superuser %}
        <a class="btn btn-outline-secondary" href="{% url 'blog:blog_create' %}">Добавить статью</a>
        {% endif %}
    </div>
    <br>
    <div class="row">
        {% for object in object_list %}

        <div class="col">
            <div class="card text-center">
                <div class="card-header">
                    {{object.title}}
                </div>
                <div class="card-body">

                    <p class="card-text">{{object.body|slice:":100"}}</p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'blog:blog_detail' object.pk %}" class="btn btn-primary">Подробнее</a>
                    {% endif %}

                </div>
                <div class="card-footer">
                    <h6>
                    </h6>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}